### ISSUE TITLE
0.1 Feature Roadmap

### ISSUE THREAD

**Issue by chrisnicola** [WealthBar/angular-d3#1]
Features planned for version 0.1

- [x] Basic chart forms for: Area, Line and Bars
- [x] Support for Donut/Pie charts
- [x] Supports multiple axis and multiple charts can be stacked
- [x] Dynamically updating charts supporting animations
- [ ] Support for dynamically updating time series data (with animations)
- [x] Data source directives to declaratively specify and load external data sources and support D3's built in parsers for CSV, TSV, etc.
- [ ] Support for customizable chart legends
- [ ] Mouse-over and touch-based overlay support
- [ ] Improved documentation site
